groups:
- name: pmacct_traffic.rules
  interval: 1m
  rules:
    # Traffic by MAC
    - record: pmacct_traffic_bytes_total_by_mac
      expr: sum(increase(pmacct_traffic_bytes_total[5m])) by (src_mac, source)
