{
 "title": "FlowHound - Top Talkers",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "topn", "label": "Top N", "query": "5,10,15,20,25,50,100" }
  ]
 },
 "panels": [
  {
   "title": "Top ${topn} Data use by MAC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(${topn}, sum(rate(pmacct_traffic_bytes_total[$__range])) by (src_mac, source))",
     "legendFormat": "{{src_mac}} {{source}}"
    }
   ]
  },
  {
   "title": "Top ${topn} Uploaders",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(${topn}, increase(pmacct_traffic_bytes_total_upload_by_src_ip[$__range]))",
     "legendFormat": "{{src_ip}} {{source}}"
    }
   ]
  },
  {
   "title": "Top ${topn} Downloaders",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(${topn}, increase(pmacct_traffic_bytes_total_download_by_dst_ip[$__range]))",
     "legendFormat": "{{dst_ip}} {{source}}"
    }
   ]
  }
 ]
}